on:
  - push

permissions:
  contents: read
  packages: write

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6    
    - name: build binary
      if: github.ref != 'refs/heads/main'
      run: go build ./cmd/...
    - name: unit tests
      run: go test ./...
    - uses: buildpacks/github-actions/setup-pack@v5.0.0
      if: github.ref == 'refs/heads/main'
    - name: build image
      run: |
        IMAGE=$(echo ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA | tr '[:upper:]' '[:lower:]')
        pack build $IMAGE -B paketobuildpacks/builder-jammy-buildpackless-static -b paketo-buildpacks/go@4.19.7
      if: github.ref == 'refs/heads/main'
    - name: connect to registry
      if: github.ref == 'refs/heads/main'
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: push image
      if: github.ref == 'refs/heads/main'
      run: |
        IMAGE=$(echo ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA | tr '[:upper:]' '[:lower:]')
        docker push $IMAGE
